# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapViewer
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire', '4.7'
  pod 'AlamofireObjectMapper', '5.0'

  target 'MapViewerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapViewerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
